# Generated by Django 4.2.16 on 2025-09-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_gainsleaderboard_raidsleaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gainsleaderboard',
            name='points',
        ),
        migrations.AddField(
            model_name='gainsleaderboard',
            name='firstplaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gainsleaderboard',
            name='secondplaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gainsleaderboard',
            name='thirdplaces',
            field=models.IntegerField(default=0),
        ),
    ]
