# Generated by Django 4.2.16 on 2025-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_remove_gainsleaderboard_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=45)),
                ('boss', models.CharField(max_length=45)),
            ],
        ),
    ]
